import json
from pathlib import Path
from typing import List, Dict, Any, Set


def detect_tech_stack(repo_dir: Path, scanned_files: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    """
    Analyzes project manifests and file extensions to detect technologies, frameworks, and tools.
    """
    tech_stack: Dict[str, Set[str]] = {
        "Languages": set(),
        "Backend Frameworks": set(),
        "Frontend Frameworks": set(),
        "Databases & Tools": set(),
    }

    extensions = {f.get("file_type", "").lower() for f in scanned_files}

    if "py" in extensions:
        tech_stack["Languages"].add("Python")
    if "ts" in extensions or "tsx" in extensions:
        tech_stack["Languages"].add("TypeScript")
    if "js" in extensions or "jsx" in extensions:
        tech_stack["Languages"].add("JavaScript")
    if "go" in extensions:
        tech_stack["Languages"].add("Go")
    if "rs" in extensions:
        tech_stack["Languages"].add("Rust")
    if "java" in extensions:
        tech_stack["Languages"].add("Java")

    # Check python requirements
    req_file = repo_dir / "requirements.txt"
    if req_file.exists():
        try:
            req_text = req_file.read_text(encoding="utf-8", errors="ignore").lower()
            if "fastapi" in req_text:
                tech_stack["Backend Frameworks"].add("FastAPI")
            if "django" in req_text:
                tech_stack["Backend Frameworks"].add("Django")
            if "flask" in req_text:
                tech_stack["Backend Frameworks"].add("Flask")
            if "sqlalchemy" in req_text:
                tech_stack["Databases & Tools"].add("SQLAlchemy")
            if "psycopg" in req_text or "asyncpg" in req_text:
                tech_stack["Databases & Tools"].add("PostgreSQL")
            if "qdrant" in req_text:
                tech_stack["Databases & Tools"].add("Qdrant Vector DB")
        except Exception:
            pass

    # Check package.json
    pkg_file = repo_dir / "package.json"
    if pkg_file.exists():
        try:
            pkg_data = json.loads(pkg_file.read_text(encoding="utf-8", errors="ignore"))
            deps = {**pkg_data.get("dependencies", {}), **pkg_data.get("devDependencies", {})}
            deps_lower = {k.lower(): v for k, v in deps.items()}

            if "react" in deps_lower:
                tech_stack["Frontend Frameworks"].add("React")
            if "vue" in deps_lower:
                tech_stack["Frontend Frameworks"].add("Vue.js")
            if "next" in deps_lower:
                tech_stack["Frontend Frameworks"].add("Next.js")
            if "vite" in deps_lower:
                tech_stack["Frontend Frameworks"].add("Vite")
            if "tailwindcss" in deps_lower or "@tailwindcss/vite" in deps_lower:
                tech_stack["Frontend Frameworks"].add("Tailwind CSS")
            if "express" in deps_lower:
                tech_stack["Backend Frameworks"].add("Express.js")
        except Exception:
            pass

    # Check Docker
    if (repo_dir / "Dockerfile").exists() or (repo_dir / "docker-compose.yml").exists():
        tech_stack["Databases & Tools"].add("Docker")

    return {category: sorted(list(items)) for category, items in tech_stack.items() if items}


def generate_repository_readme(
    repo_name: str,
    repo_dir: Path,
    scanned_files: List[Dict[str, Any]],
    ast_symbols: List[Dict[str, Any]]
) -> str:
    """
    Generates a multi-section GitHub Flavored Markdown README document based on repository analysis.
    """
    tech_stack = detect_tech_stack(repo_dir, scanned_files)

    # Classify AST symbols
    functions = [s for s in ast_symbols if s.get("symbol_type") == "function"]
    classes = [s for s in ast_symbols if s.get("symbol_type") == "class"]

    md = f"""# {repo_name}

An automated overview and technical documentation generated by **DevMind AI Platform**.

---

## 📌 Project Overview
- **Repository Name**: `{repo_name}`
- **Total Files Scanned**: `{len(scanned_files)}`
- **Extracted Code Symbols**: `{len(ast_symbols)}` (`{len(classes)}` Classes, `{len(functions)}` Functions)

---

## 🛠️ Technology Stack
"""

    if tech_stack:
        for category, techs in tech_stack.items():
            md += f"- **{category}**: {', '.join([f'`{t}`' for t in techs])}\n"
    else:
        md += "- Auto-detected file types: " + ", ".join([f"`{f.get('file_type')}`" for f in scanned_files[:5]]) + "\n"

    md += """
---

## 📂 Key File Structure
```text
"""
    # Sample top 15 files
    for f in scanned_files[:15]:
        md += f"├── {f['file_path']} ({f['size_bytes']} bytes)\n"
    if len(scanned_files) > 15:
        md += f"└── ... and {len(scanned_files) - 15} more files\n"
    md += "```\n\n---\n\n## 🧬 Core Code Architecture\n"

    if classes:
        md += "### Classes & Interfaces\n"
        for cls in classes[:10]:
            sig = cls.get("signature") or f"class {cls['name']}"
            doc = f" — *{cls['docstring']}*" if cls.get("docstring") else ""
            md += f"- `{sig}`{doc}\n"
        md += "\n"

    if functions:
        md += "### Key Functions & API Handlers\n"
        for fn in functions[:10]:
            sig = fn.get("signature") or f"def {fn['name']}()"
            doc = f" — *{fn['docstring']}*" if fn.get("docstring") else ""
            md += f"- `{sig}`{doc}\n"
        md += "\n"

    md += """---

## 🚀 Getting Started

### Prerequisites
- Ensure Python 3.10+ or Node.js runtime environment is installed.

### Setup Instructions
1. Clone or extract repository source files.
2. Install dependencies:
   ```bash
   # Python Backend
   pip install -r requirements.txt

   # JavaScript/TypeScript Frontend
   npm install
   ```
3. Run development server:
   ```bash
   # Python Server
   uvicorn app.main:app --reload

   # Frontend Client
   npm run dev
   ```

---
*Documentation auto-generated by [DevMind AI](file:///c:/Users/Mohit%20Gaonkar/Desktop/devmind-ai).*
"""
    return md.strip()
